export const jobOpenings = [
  {
    title: "Frontend Developer",
    company: "Tech Innovators Pvt Ltd",
    location: "Bengaluru, Karnataka",
    salary: "10 LPA",
    positions: 3,
    type: "Part Time",
  },
  {
    title: "Backend Developer",
    company: "CodeCraft Solutions",
    location: "Hyderabad, Telangana",
    salary: "12 LPA",
    positions: 1,
    type: "Full Time",
  },
  {
    title: "FullStack Developer",
    company: "WebGenix",
    location: "Pune, Maharashtra",
    salary: "15 LPA",
    positions: 2,
    type: "Full Time",
  },
  {
    title: "Data Scientist",
    company: "DataWorks",
    location: "Mumbai, Maharashtra",
    salary: "18 LPA",
    positions: 3,
    type: "Part Time",
  },
  {
    title: "UI/UX Designer",
    company: "Creative Minds",
    location: "Chennai, Tamil Nadu",
    salary: "8 LPA",
    positions: 2,
    type: "Full Time",
  },
  {
    title: "Mobile App Developer",
    company: "Appify",
    location: "Noida, Uttar Pradesh",
    salary: "9 LPA",
    positions: 4,
    type: "Hourly",
  },
];
